[package]
name = "thermite-protocol"
version = "0.1.0"
edition = "2021"

[lib]
name = "thermite_protocol"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.3"
uuid = { version = "1.11", features = ["serde", "v4"] }
